MAX_SEED = 100000000
RANDOM_TEXT_QUEUE_MAX_SIZE = 500 

SEED = "seed"
TEMPERATURE = "temperature"
TEXT_PROMPTS = "text_prompts"
CHAT_SYNTH_GEN_FUNC_NAME = "generate_chat_synthetic"

SYNTHETIC_DATA_EXPIRATION_TIME = 3  # 3 seconds
